language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run lint"
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: a36a6a56f5deee0eff3a6e9a9d07e4f5e155701c
  local_dir: dist
  on:
    branch: master